esphome:
  name: mcp23017
  # on_boot:
  #   priority: -100
  #   then:
  #     - delay: 5s 
  #     - switch.turn_on: led_switch

esp32:
  #board: esp32-c3-devkitm-1
  variant: esp32c3
  framework:
    type: esp-idf
  partitions: partitions.csv

# logger:
#   hardware_uart: UART0

i2c:
  sda: GPIO8
  scl: GPIO9
  scan: true
  id: bus_a

# 2. Register the MCP23017 Hub
mcp23017:
  - id: 'mcp23017_hub'
    address: 0x20
    interrupt_pin: GPIO7

#Create a Switch to control the LED on GPA0
switch:
  - platform: gpio
    id: led_switch
    name: "MCP23017 LED"
    pin:
      mcp23xxx: mcp23017_hub
      number: 0 # Pin 0 on MCP23017 is GPA0
      mode: output

# button on GPA1
binary_sensor:
  - platform: gpio
    name: "MCP23017 Input Button B0"
    pin:
      mcp23xxx: mcp23017_hub
      number: 8        # Pin 8 on MCP23017 is B0
      inverted: true           
      mode:
        input: true     
        pullup: true     
    on_press:
    - switch.turn_on: led_switch
  - platform: gpio
    name: "MCP23017 Input Button B2"
    pin:
      mcp23xxx: mcp23017_hub
      number: 10  # Pin 10 on MCP23017 is B2
      mode:
        input: true     
        pullup: true         
      inverted: true
    on_press:
      - switch.turn_off: led_switch