esphome:
  name: einktest
  name_add_mac_suffix: false
  # on_boot:
  #   - priority: -100
  #     then:
  #       - logger.log: Hello World!

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
  level: VERY_VERBOSE

spi:
  clk_pin: GPIO4
  mosi_pin: GPIO5


  #font:
  # - file:
  #     type: gfonts
  #     family: Roboto
  #     weight: 900
  #   id: roboto
  #   size: 16

font:
  - file: "gfonts://Roboto"
    id: roboto
    size: 20

display:
  - platform: waveshare_epaper
    # model: gdey029t94
    model: 2.90inv2
    cs_pin: 
      number: GPIO15
      
    dc_pin: 
      number: GPIO21
    busy_pin: 
      number: GPIO23
      inverted: false
      
    reset_pin: 
      number: GPIO22
    reset_duration: 100ms
    #rotation: 270
    full_update_every: 30
    lambda: |-
      it.filled_rectangle(40, 40, 30, 42);
      //it.print(30, 30, id(roboto), "Hello World!");
      //it.fill(Color(255,255,0));//yellow


