[wokwi]
version = 1
firmware = '.esphome/build/einktest/.pioenvs/einktest/firmware.elf'
elf = '.esphome/build/einktest/.pioenvs/einktest/firmware.elf'

# wifi SSID is Wokwi-GUEST
# https://docs.wokwi.com/guides/esp32-wifi
