substitutions:
  tag: mohan

esphome:
  name: helloworld
  on_boot:
    - priority: -100
      then:
        - logger.log:
            format: "Hello ESP32!"
            level: INFO
            tag: ${tag}
        - output.turn_on: red_led

esp32:
  variant: esp32c3
  framework:
    type: arduino
  partitions: partitions.csv

logger:
  hardware_uart: UART0
  level: INFO
  logs:
    logger: NONE
    app: NONE
    component: NONE
    

output:
  - platform: gpio
    pin: GPIO4
    id: red_led
