esphome:
  name: helloworld
  on_boot:
    - priority: -100
      then:
        - output.turn_on: red_led

esp32:
  board: esp32dev
  framework:
    type: arduino

output:
  - platform: gpio
    pin: GPIO2
    id: red_led
