[wokwi]
version = 1
firmware = '.esphome/build/helloworld/.pioenvs/helloworld/firmware.bin'
elf = '.esphome/build/helloworld/.pioenvs/helloworld/firmware.elf'

# wifi SSID is Wokwi-GUEST
# https://docs.wokwi.com/guides/esp32-wifi
