substitutions:
  tag: mohan
  gif_file: "test.gif"
  tft_width: 320
  tft_height: 240


esphome:
  name: gifesp32c3
  on_boot:
    priority: -100
    then:
      - lambda: |-
          uint32_t free_heap = ESP.getFreeHeap();
          uint32_t free_flash = ESP.getFreeSketchSpace();
          ESP_LOGI("boot_info", "------------------------------------");
          ESP_LOGI("boot_info", "RAM Free: %u bytes (%u KB)", free_heap, free_heap/1024);
          ESP_LOGI("boot_info", "Flash Free (Program Space): %u bytes (%u KB)", free_flash, free_flash/1024);
          ESP_LOGI("boot_info", "------------------------------------");

esp32:
  variant: esp32c3
  framework:
    type: arduino
  partitions: partitions.csv

spi:
  clk_pin: GPIO3
  mosi_pin: GPIO4

logger:
  hardware_uart: UART0
  baud_rate: 9600
  logs:
    logger: INFO
    debug: INFO

wifi:
  ssid:  Wokwi-GUEST



animation:
  - file: ${gif_file}
    id: my_animation
    type: RGB565
    resize: 80x80

display:
  - platform: mipi_spi
    model: ILI9341
    id: mylcd
    dc_pin: GPIO6
    cs_pin: GPIO5
    reset_pin: GPIO7
    rotation: 0
    invert_colors: false
    update_interval: 350ms
    color_order: bgr
    dimensions:
      width: ${tft_width}
      height: ${tft_height}
      offset_width: "0"
    # transform:
    #   swap_xy: true
    #   mirror_x: false
    #   mirror_y: false
    lambda: |-
      id(my_animation).next_frame();
      it.image(120 - 35 , 160 - 35, id(my_animation));




