# Taken from https://github.com/esphome/wake-word-voice-assistants/blob/main/esp32-s3-box-3/esp32-s3-box-3.yaml

esphome:
  name: pictureframe
  on_boot:
    - priority: -100
      then:
        - logger.log: Hello World!

esp32:
  board: esp32s3box
  # flash_size: 16MB
  # cpu_frequency: 240MHz
  framework:
    type: arduino
    # type: esp-idf
    # sdkconfig_options:
    #   CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
    #   CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
    #   CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"  

# psram:
#   mode: octal
#   speed: 80MHz

logger:

