substitutions:
  tagname: mohan

esphome:
  name: testpsram
  on_boot:
    - priority: 800
      then:
        - logger.log: ""
        - logger.log: -------------------------------------------------------      
        - lambda: |-
            ESP_LOGI("${tagname}", "PSRAM: %zu bytes AVAILABLE: %zu", ESP.getPsramSize(), ESP.getFreePsram());
        - logger.log: -------------------------------------------------------   

esp32:
  board: esp32-s3-devkitm-1
  framework:
    type: arduino

psram:
  mode: octal
  speed: 80MHz

logger:
  hardware_uart: UART0





