esphome:
  name: wledesphome

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# wifi:
#   ssid: Wokwi-GUEST

# psram:
#   mode: octal
#   speed: 80MHZ

# logger:

# wifi:
#   ssid: !secret wifi_ssid
#   password: !secret wifi_password

# captive_portal:

#api:

# ota:
#   - platform: esphome

# web_server:
#   port: 80

# wled:

light:
  - platform: esp32_rmt_led_strip
    rgb_order: RGB
    chipset: WS2812
    pin: GPIO3
    num_leds: 16
    name: "NeoPixel"
    id: my_light
    effects:
      - pulse:
    # effects:
    #   - wled:
    # effects:
    #   - lambda:
    #       name: booo
    #       update_interval: 1s
    #       lambda: |-
    #         id(led_script).execute();
            

    restore_mode: ALWAYS_ON

# script:
#   - id: led_script
#     then:
#       - logger.log: "boo"
#       - light.turn_on:
#           id: my_light
#           brightness: 100%
#           green: 100%
#       - light.addressable_set:
#           id: my_light
#           range_from: 2
#           range_to: 3
#           color_brightness: 100%
#           red: 100%



