esphome:
  name: webserver
  on_boot:
    - priority: -100
      then:
        - logger.log: Hello World!

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

wifi:
  ssid: Wokwi-GUEST

web_server:
  port: 80

output:
  - platform: gpio
    pin: GPIO2
    id: led_pin

light:
  - platform: binary
    name: "LED"
    output: led_pin
    id: led_light

button:
  - platform: template
    name: "Toggle LED"
    on_press:
      - light.toggle: led_light

 