

#### You will need to let simulation run for about 45 seconds
#### as it needs connect to wifi download image and decode.

substitutions:
  tft_width: 320
  tft_height: 240

esphome:
  name: ili9341
  on_boot:
    - priority: 800
      then:
        - lvgl.canvas.draw_rectangle:
            id: colorbarcanvas
            x: 0
            y: 0
            width: 45
            height: 210
            bg_color: white
        - lvgl.canvas.draw_rectangle:
            id: colorbarcanvas
            x: 45
            y: 0
            width: 46
            height: 210
            bg_color: yellow
        - lvgl.canvas.draw_rectangle:
            id: colorbarcanvas
            x: 91
            y: 0
            width: 46
            height: 210
            bg_color: cyan
        - lvgl.canvas.draw_rectangle:
            id: colorbarcanvas
            x: 137
            y: 0
            width: 46
            height: 210
            bg_color: lime
        - lvgl.canvas.draw_rectangle:
            id: colorbarcanvas
            x: 183
            y: 0
            width: 46
            height: 210
            bg_color: magenta
        - lvgl.canvas.draw_rectangle:
            id: colorbarcanvas
            x: 229
            y: 0
            width: 46
            height: 210
            bg_color: red
        - lvgl.canvas.draw_rectangle:
            id: colorbarcanvas
            x: 275
            y: 0
            width: 45
            height: 210
            bg_color: blue

esp32:
  board: esp32-s3-devkitm-1
  cpu_frequency: 240MHz
  framework:
    type: arduino

psram:
  mode: quad
  speed: 120MHz

# logger:
#   hardware_uart: UART0

wifi:
  ssid:  Wokwi-GUEST
  on_connect: 
    then:
      - component.update: onlineimage

http_request:
  verify_ssl: false
  timeout: 10s

image:
  - file: empty.png
    type: binary
    id: emptyimage
     
online_image:
  # url: https://upload.wikimedia.org/wiktionary/en/a/a5/Shocked_Pikachu.png
  url: https://cdn.jsdelivr.net/gh/mohankumargupta/wokwi-vscode-examples@refs/heads/main/ili9341/animal.png
  format: png
  #resize: 320x240
  type: rgb565
  id: onlineimage
  on_download_finished: 
    then:
      - lvgl.image.update:
          id: lvglimage
          src: onlineimage
      - lvgl.page.show: animal

spi:
  clk_pin: GPIO14
  mosi_pin: GPIO13

display:
  - platform: mipi_spi
    model: ILI9341
    id: mylcd
    dc_pin: GPIO2
    #reset_pin: 0
    cs_pin: GPIO15
    rotation: 0
    invert_colors: false
    update_interval: never
    #color_depth: 8
    #show_test_card: true
    color_order: bgr
    dimensions:
      width: ${tft_width}
      height: ${tft_height}
      offset_width: "0"
    transform:
      swap_xy: true
      mirror_x: false
      mirror_y: false

lvgl:
  buffer_size: 100%
  bg_color: black
  text_color: white
  pages:
    - id: colorbars
      widgets:
        - canvas:
            width: 320
            height: 240
            id: colorbarcanvas
    - id: animal
      widgets:
        - image:
            src: emptyimage
            id: lvglimage

