    name: Hello World Workflow

    on:
      workflow_dispatch:
        inputs:
          binary_name:
            description: 'Enter the name of the YAML file (without .yaml extension)'
            required: true
            type: string
            default: 'default'

    jobs:
      compile:
        name: ${{ github.event.inputs.binary_name }} 
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - uses: esphome/build-action@v6
            with:
              yaml-file: ${{ github.event.inputs.binary_name }}



