    name: Compile esphome
    on:
      workflow_dispatch:
        inputs:
          binary_name:
            description: 'Enter the name of the YAML file (without .yaml extension)'
            required: true
            type: choice
            default: 'helloworld'
            options:
              - helloworld
              - webserver
              - wledesphome  
    jobs:
      compile:
        name: ${{ github.event.inputs.binary_name }} 
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - uses: esphome/build-action@v6
            with:
              yaml-file: ${{ github.event.inputs.binary_name }}/${{ github.event.inputs.binary_name }}.yaml
          - name: Upload factory binary
            uses: actions/upload-artifact@v4
            with:
              name: ${{ github.event.inputs.binary_name }}-factory-bin
              path: ${{ github.event.inputs.binary_name }}/${{ github.event.inputs.binary_name }}.factory.bin
              if-no-files-found: error
              retention-days: 7      
          - name: Upload ELF file
            uses: actions/upload-artifact@v4
            with:
              name: ${{ github.event.inputs.binary_name }}-elf
              path: ${{ github.event.inputs.binary_name }}/${{ github.event.inputs.binary_name }}.elf
              if-no-files-found: error
              retention-days: 7
