set shell := ["sh", "-c"]
set windows-shell := ["powershell", "-c"]

compile: compile_only merge_bin

compile_mega: compile_only littlefs merge_bin

compile_only:
    uvx --python 3.12 --with=pip esphome compile gifesp32c3lvgllittlefs.yaml

littlefs:
    mklittlefs -c data -p 256 -b 4096 -s 2031616 littlefs.bin

merge_bin:
    uvx --python 3.12 --with=pip esptool --chip esp32c3 merge-bin -o final.bin 0x00 .esphome/build/gifesp32c3lvgllittlefs/.pioenvs/gifesp32c3lvgllittlefs/firmware.factory.bin 0x210000 littlefs.bin 


