[wokwi]
version = 1
firmware = '.esphome/build/gifesp32c3lvgllittlefs/.pioenvs/gifesp32c3lvgllittlefs/firmware.bin'
#elf = '.esphome/build/gifesp32c3lvgllittlefs/.pioenvs/gifesp32c3lvgllittlefs/firmware.elf'

# wifi SSID is Wokwi-GUEST
# https://docs.wokwi.com/guides/esp32-wifi
